map_type: costmap
transform_tolerance: 0.5
meter_scoring: true
footprint: [[0.52, 0.35], [0.52, -0.35], [-0.52, -0.35], [-0.52, 0.35]]
footprint_padding: 0.10

inflater_layer:
  enabled: true
  cost_scaling_factor: 3.0
  inflation_radius: 1.20
