geometry_msgs/PolygonStamped region
float32 operation_width_m
float32 overlap_ratio
bool allow_reverse_transit
string map_digest
---
bool success
string message
string plan_id
nav_msgs/Path planned_path
float32 requested_area_m2
float32 reachable_area_m2
float32 unreachable_area_m2
float32 sweep_angle_rad
uint32 swath_count
uint32 segment_count
string map_digest
