"""Testable configuration and TEB parameter-interface core."""

from .config import (
    ConfigValidationError,
    load_yaml_mapping,
    validate_a_teb,
    validate_experiment_contract,
    validate_runtime_config,
)
from .safety_gate import SimulationGateError, SimulationWriteContext, require_t02_simulation
from .teb_parameter_client import (
    AckMismatchError,
    ParameterDescriptionError,
    ParameterRangeError,
    ParameterTimeoutError,
    ParameterTypeError,
    ReadbackMismatchError,
    RestoreError,
    RosDynamicReconfigureBackend,
    TebParameterClient,
    TebParameterError,
    specs_as_dict,
    validate_parameter_interface,
)
from .episode_state_machine import EpisodeOutcome, EpisodeStateMachine, TransitionDisposition
from .fallback_policy import ConservativeFallbackPolicy, FallbackDecision, FallbackUnavailable
from .parameter_projection import (
    CandidateRejected,
    ParameterLimit,
    ParameterProjector,
    ProjectionConfigurationError,
    ProjectionResult,
)
from .reward_cost import (
    FeedbackSample,
    RewardCostResult,
    RewardWeights,
    WindowEvents,
    calculate_reward_and_cost,
)
from .safety_margin_filter import (
    SafetyDecision,
    SafetyMarginConfig,
    SafetyMarginFilter,
    SafetyMode,
)
from .state_builder import (
    DirectionalScanCoverage,
    HistoryWindow,
    ScanAngularMetadata,
    StateBuilder,
    StateFrame,
    lidar_sector_quantiles,
)
from .timing import ActivationTracker, ActivationWindow, MonotonicRosTime, synchronize_stamps
from .training_environment import (
    ActivationPoll,
    EnvironmentConfig,
    FeedbackWindow,
    FixedPolicy,
    ObservationInput,
    ParameterWriteReceipt,
    RandomSmallPolicy,
    SafeParameterDecision,
    TrainingEnvironment,
    TrainingEnvironmentError,
)
from .baseline_policy import (
    CausalRuleTebPolicy,
    ObservationLayout,
    RULE_MODES,
    RuleThresholds,
)
from .semantic_action import (
    FrozenSemanticMapping,
    ResidualSemanticActionResult,
    ResidualSemanticMapping,
    SemanticActionError,
    SemanticActionResult,
)
from .direct_theta_action import (
    DirectThetaActionError,
    DirectThetaActionResult,
    DirectThetaMapping,
)
from .sac_fairness import SacFairnessError, load_and_validate_sac_pair
from .safety_ablation import NoFallbackSafetyAdapter, SAFETY_ABLATIONS
from .shadow_runtime import (
    FeatureEnvelope,
    ShadowDecision,
    ShadowRuntime,
    ShadowRuntimeConfig,
    ShadowRuntimeError,
    ThetaEmaSmoother,
)

__all__ = [
    "ConfigValidationError",
    "load_yaml_mapping",
    "validate_a_teb",
    "validate_experiment_contract",
    "validate_runtime_config",
    "SimulationGateError",
    "SimulationWriteContext",
    "require_t02_simulation",
    "AckMismatchError",
    "ParameterDescriptionError",
    "ParameterRangeError",
    "ParameterTimeoutError",
    "ParameterTypeError",
    "ReadbackMismatchError",
    "RestoreError",
    "RosDynamicReconfigureBackend",
    "TebParameterClient",
    "TebParameterError",
    "specs_as_dict",
    "validate_parameter_interface",
    "EpisodeOutcome",
    "EpisodeStateMachine",
    "TransitionDisposition",
    "ConservativeFallbackPolicy",
    "FallbackDecision",
    "FallbackUnavailable",
    "CandidateRejected",
    "ParameterLimit",
    "ParameterProjector",
    "ProjectionConfigurationError",
    "ProjectionResult",
    "FeedbackSample",
    "RewardCostResult",
    "RewardWeights",
    "WindowEvents",
    "calculate_reward_and_cost",
    "SafetyDecision",
    "SafetyMarginConfig",
    "SafetyMarginFilter",
    "SafetyMode",
    "HistoryWindow",
    "DirectionalScanCoverage",
    "ScanAngularMetadata",
    "StateBuilder",
    "StateFrame",
    "lidar_sector_quantiles",
    "ActivationTracker",
    "ActivationWindow",
    "MonotonicRosTime",
    "synchronize_stamps",
    "ActivationPoll",
    "EnvironmentConfig",
    "FeedbackWindow",
    "FixedPolicy",
    "ObservationInput",
    "ParameterWriteReceipt",
    "RandomSmallPolicy",
    "SafeParameterDecision",
    "TrainingEnvironment",
    "TrainingEnvironmentError",
    "CausalRuleTebPolicy",
    "ObservationLayout",
    "RULE_MODES",
    "RuleThresholds",
    "FrozenSemanticMapping",
    "SemanticActionError",
    "SemanticActionResult",
    "DirectThetaActionError",
    "DirectThetaActionResult",
    "DirectThetaMapping",
    "SacFairnessError",
    "load_and_validate_sac_pair",
    "NoFallbackSafetyAdapter",
    "SAFETY_ABLATIONS",
    "FeatureEnvelope",
    "ShadowDecision",
    "ShadowRuntime",
    "ShadowRuntimeConfig",
    "ShadowRuntimeError",
    "ThetaEmaSmoother",
]
